### ISSUE TITLE
图片不支持identity类型的动态属性

### ISSUE THREAD

**Issue by jiqin111** [maptalks/maptalks.js#702]
**maptalks's version and what browser you use?**
maptalks v0.40.1

**Issue description**
在使用markerFile设置图片时，发现不能根据属性值来展示不同的图片，不支持identify的动态属性

**Please provide a reproduction URL (on any jsfiddle like site)**
http://jsfiddle.net/rqf7ojey/2/

**Comment by JoyTroy** [comment]
不大明白你的需求，不过我有个用于图片的方案不知道有没有帮助，也可用于gif图片。
以下是实现图片倾斜并自转的需求，使用UIMarker实现，分三层div，
1、根容器元素只设置宽高，确保根据经纬度定位；
2、父元素控制倾斜---transform；
3、子元素控制自转---animation、同时引入图片；
(animation和transform同时在一个div中使用会导致transform失效)

```js
var dom = document.createElement('div');
dom.className = groupClass; //设置为根容器元素
var par = document.createElement('div');
par.className = 'par-group'; //设置为父元素
var sub = document.createElement('div');
sub.className = 'sub-group'; //设置为子元素
par.appendChild(sub);
dom.appendChild(par);
var uimarker = new maptalks.ui.UIMarker(coord, {
	draggable : false,
	content : dom
}).addTo(map);
```
```css
transform: rotateX(55deg) rotateY(2deg) !important; 
animation: rotate 30s linear 0s infinite normal ;
@keyframes rotate{
	from{transform:rotate(0deg)}
	to{transform:rotate(360deg)}
}
```
