### ISSUE TITLE
tooltip cannot set width and height

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.js#898]
**maptalks's version and what browser you use?**
----

**Issue description**
----

tooltip cannot set width and height

https://codepen.io/deyihu/pen/mYyozY

```js
 buildOn() {
        const dom = createEl('div');
      // this is fixed
      // const options = this.options;
        if (options.height) {
            dom.style.height = options.height + 'px';
        }
        if (options.width) {
            dom.style.width = options.width + 'px';
        }
        const cssName = this.options.cssName;
        if (!cssName && options.height) {
            dom.style.lineHeight = options.height + 'px';
        }
        dom.innerHTML = `<div class="${cssName}">${this._content}</div>`;
        return dom;
    }


```

options 没有拿自身的，而是用了全局的变量

这个问题主要有tooltip的内容想换行发现的，
另外 maptalks-tooltip 

```css
.maptalks-tooltip {
  display: block;
  background: #fff;
  border: 1px solid #b4b3b3;
  padding: 0px 4px 0px 4px;
  height:24px;
  line-height:24px;
  font-size:14px;
  white-space: nowrap;
}

```
的高度限制死了为 24px（虽然我可以通过css覆盖来更改）,还是建议设为 100%，

**Please provide a reproduction URL (on any jsfiddle like site)**
----
